# -*- coding: utf-8 -*-
"""Filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_wX0ozp3l2slPIVgdRNdeZgDZe-PFnx
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline


def create_filter_model(X_train, y_train):
    classifier = LogisticRegression(max_iter=500)
    tfidf_vector = TfidfVectorizer()
    pipe = Pipeline([('vectorizer', tfidf_vector),
                     ('classifier', classifier)])
    return pipe.fit(X_train, y_train)
